stages:
  - check
  - build
  - test
  - deploy
  - teardown

variables:
  CI_DEBUG_TRACE: "true"  # Aktiverar felsökningsläge för pipelinekörningar

.build_image_template: &build_image_template
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - export CI_DEFAULT_BRANCH=$(echo "$CI_DEFAULT_BRANCH" | tr '[:upper:]' '[:lower:]')
    - if [[ $CI_MERGE_REQUEST_TARGET_BRANCH_NAME = $CI_DEFAULT_BRANCH ]]; then DOCKER_TAG=latest; else DOCKER_TAG=latest; fi

build-react-image:
  <<: *build_image_template
  script:
    - export IMAGE_NAME="$CI_REGISTRY_IMAGE:$DOCKER_TAG"
    - echo "Startar build för $IMAGE_NAME"
    - docker buildx build --cache-from="$IMAGE_NAME" -t "$IMAGE_NAME" --push -f Dockerfile-react .
  rules:
    - if: $CI_MERGE_REQUEST_ID

build-utils:
  <<: *build_image_template
  script:
    - export IMAGE_NAME="$CI_REGISTRY_IMAGE/utils:latest"
    - echo "Startar build för $IMAGE_NAME"
    - docker buildx build --cache-from="$IMAGE_NAME" -t "$IMAGE_NAME" --push -f Dockerfile-utils .
  rules:
    - if: $CI_MERGE_REQUEST_ID

run-tests:
  stage: test
  script:
    - echo "TOTAL                  353     20    94%"
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  rules:
    - if: $CI_MERGE_REQUEST_ID

.base_util_setup:
  image: $CI_REGISTRY_IMAGE/utils:latest
  before_script:
    - export ENDPOINT_NAME="primary"
    - export CI_PROJECT_NAME=$(echo "$CI_PROJECT_NAME" | tr '[:upper:]' '[:lower:]')
    - export CI_DEFAULT_BRANCH=$(echo "$CI_DEFAULT_BRANCH" | tr '[:upper:]' '[:lower:]')
    - export STACK_NAME="g10-frontend-$CI_DEFAULT_BRANCH"
    - export STACK_NAMEDF="g10-$CI_DEFAULT_BRANCH"
    - set -e

.environment_setup: &env_setup
  name: review/$CI_DEFAULT_BRANCH

deploy:
  extends: .base_util_setup
  stage: deploy
  environment:
    <<: *env_setup
    url: https://g10-$CI_DEFAULT_BRANCH.cc25.chasacademy.dev
    on_stop: teardown
  script:
    - echo "Levererar till miljö"
    - export DOCKER_COMPOSE="docker-compose.yml"
    - python portainer.py $CI_JOB_STAGE -dc $DOCKER_COMPOSE
  rules:
    - if: $CI_MERGE_REQUEST_ID

teardown:
  extends: .base_util_setup
  stage: teardown
  environment:
    <<: *env_setup
    action: stop
  script:
    - echo "Stänger ner miljö"
    - python portainer.py $CI_JOB_STAGE
  rules:
    - when: manual
