version: '3.8' # Se till att du använder en version som stöder Swarm-funktioner
services:
  equilog-frontend:
    image: registry.chasacademy.dev/cc25group-10/frontend:${DOCKER_TAG}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      # replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${STACK_NAME}-http.rule=Host(`${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.${STACK_NAME}-http.entrypoints=http
        - traefik.http.routers.${STACK_NAME}-http.middlewares=https-redirect
        - traefik.http.routers.${STACK_NAME}-https.rule=Host(`${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.${STACK_NAME}-https.entrypoints=https
        - traefik.http.routers.${STACK_NAME}-https.tls=true
        - traefik.http.routers.${STACK_NAME}-https.tls.certresolver=le
        - traefik.http.routers.${STACK_NAME}-https.tls.domains[0].main=cc25.chasacademy.dev
        - traefik.http.routers.${STACK_NAME}-https.tls.domains[0].sans=*.cc25.chasacademy.dev
        - traefik.http.services.${STACK_NAME}.loadbalancer.server.port=5173
    environment:
      - VITE_API_BASE_URL=https://api.g10-main.cc25.chasacademy.dev
      - VITE_AZURE_STORAGE_URL=https://azuritegrup10blob.cc25.chasacademy.dev/devstoreaccount1/equilog-media

networks:
  traefik-public:
    external: true
